packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@trpc/client": ^11.2.0
  "@trpc/server": ^11.2.0
  superjson: ^2.2.1
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8
  dotenv-cli: ^7.4.2
  "@t3-oss/env-core": ^0.11.1
  prettier-plugin-tailwindcss: ^0.6.5
  typescript-eslint: ^8.0.0
  hono: ^4.6.9
  "svelte": ^5.19.0
  "@sveltejs/kit": ^2.16.0
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  "@sveltejs/adapter-auto": ^4.0.0
  "@sveltejs/adapter-node": ^5.2.9
  "@sveltejs/enhanced-img": ^0.4.1
  "svelte-check": ^4.0.0
  "mdsvex": ^0.12.3
  "svelte-seo": ^1.6.1
  "bits-ui": "1.0.0-next.84"
  "@date-fns/tz": ^1.2.0
  "lucide-svelte": ^0.473.0
  # Waiting for this to be merged: https://github.com/Menci/vite-plugin-top-level-await/pull/63
  vite: 6.0.6
  vitest: 3.0.4
  clsx: ^2.1.1

  "@langchain/community": ^0.3.45
  "@langchain/core": ^0.3.57
  "@langchain/google-vertexai": ^0.2.10
  "@langchain/langgraph": ^0.2.74

  "@sentry/bun": ^9.23.0
  "@sentry/sveltekit": ^9.23.0
